#!/bin/bash

export CATALINA_PID=~/apache-tomcat-7.0.42/catalina.pid
kill -9 `cat $CATALINA_PID`
cd swf/
mvn install
rm ~/apache-tomcat-7.0.42/webapps/poker/poker.swf
cp ../java/target/poker/poker.swf ~/apache-tomcat-7.0.42/webapps/poker/
cd ../
~/apache-tomcat-7.0.42/bin/catalina.sh jpda start
tail -f ~/apache-tomcat-7.0.42/logs/catalina.out
