#!/bin/bash

export CATALINA_PID=~/apache-tomcat-7.0.42/catalina.pid
kill -9 `cat $CATALINA_PID`
cd java/
mvn install
rm -rf ~/apache-tomcat-7.0.42/webapps/poker
rm ~/apache-tomcat-7.0.42/webapps/poker.war
cd ../
cp java/target/poker.war ~/apache-tomcat-7.0.42/webapps/
~/apache-tomcat-7.0.42/bin/catalina.sh jpda start
tail -f ~/apache-tomcat-7.0.42/logs/catalina.out
