#!/bin/bash

wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_King_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Queen_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Jack_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_10_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_9_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_8_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_7_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_6_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_5_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_4_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_3_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_2_of_spades.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Ace_of_spades.svg

wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_King_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Queen_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Jack_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_10_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_9_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_8_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_7_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_6_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_5_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_4_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_3_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_2_of_hearts.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Ace_of_hearts.svg

wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_King_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Queen_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Jack_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_10_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_9_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_8_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_7_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_6_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_5_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_4_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_3_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_2_of_clubs.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Ace_of_clubs.svg

wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_King_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Queen_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Jack_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_10_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_9_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_8_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_7_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_6_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_5_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_4_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_3_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_2_of_diamonds.svg
wget http://openclipart.org/people/nicubunu/nicubunu_Ornamental_deck_Ace_of_diamonds.svg
