package com.flexpoker.model;

public enum GameEventType {

    HAND_DEALT, CHECK, FOLD, CALL, RAISE, HAND_COMPLETE, WON_HAND, PLAYER_OUT,
    FLOP_DEALT, TURN_DEALT, RIVER_DEALT, BLINDS_INCREASED;

}
