package com.flexpoker.web.init

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SecurityWebApplicationInitializer : AbstractSecurityWebApplicationInitializer()